apiVersion: v1
kind: Pod
metadata:
  name: app-nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: nginx-pv
      mountPath: /users/share/nginx/html
  volumes:
  - name: nginx-pv
    persistentVolumeClaim:
      claimName: ebs-claim